#!/usr/bin/env bash
# Printed into a new session's context so it starts knowing the things that
# otherwise cost a session an hour to rediscover: where Playwright lives, that
# the HTML is generated, and whether the toolchain this repo needs is present.
set -u
cd "$(dirname "$0")/.." || exit 0

say() { printf '%s\n' "$1"; }

say "safehouseins.com — every .html is generated by a script in tools/."
say "Never hand-edit generated HTML; change the generator. See CLAUDE.md."
say ""

# Pillow is the dependency the tools actually reach for. numpy is imported by
# cutout.py alone, so a missing numpy only matters if you are cutting studio
# backgrounds off product renders. Report rather than install: this may not be
# a machine where installing is wanted.
py_have() { python3 -c "import $1" 2>/dev/null && echo yes || echo no; }
say "python3 $(python3 -V 2>&1 | cut -d' ' -f2)  Pillow=$(py_have PIL)"
[ "$(py_have numpy)" = "no" ] && say "numpy absent — only tools/cutout.py needs it."

# Playwright is on the image, not in the project. Without NODE_PATH every
# require('playwright') fails and it looks like it is not installed.
if [ -d /opt/node22/lib/node_modules/playwright ]; then
  say "Playwright: global. Use NODE_PATH=/opt/node22/lib/node_modules"
  say "Do NOT run 'playwright install' or add it to the project."
else
  say "Playwright: not found at the usual path; check before writing browser tests."
fi

say ""
say "Rebuild (all of them, sitemap last — generators share modules):"
say "  for g in genabout gencareers genlegal genmakes genguides genproduct gencities genpreview; do python3 tools/\$g.py || break; done && python3 tools/gensitemap.py"

# A dirty tree at session start is usually a previous session's unfinished
# work, and knowing that up front prevents it being mistaken for your own.
n=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
[ "${n:-0}" != "0" ] && say "" && say "Note: $n uncommitted change(s) already in the tree."
exit 0
