"""The city list behind the local landing pages.

Each row is (slug, name, county, tags, neighbors).

`tags` decides which of the written sections a page gets, and it is the reason
these are not doorway pages: a border city page argues about Mexican policies
and foreign licenses, an oil-basin page argues about work trucks and commute
mileage, a coastal page argues about wind and flood. Two cities with the same
tags still differ by county, by state minimums and by who they link to.

Nothing here is a statistic. Counties, state minimum limits and which cities sit
on the river are all checkable facts. Average premiums, population counts and
"drivers in Dallas save $X" are not in this file on purpose — inventing them
would be the fastest way to make the whole set worthless.

Only Texas and New Mexico appear, because those are the two licenses the agency
holds. A landing page for a city we cannot write in is a page that wastes the
visitor's time.
"""

TX_MIN = '30/60/25'   # $30k per person, $60k per accident, $25k property damage
NM_MIN = '25/50/10'   # $25k per person, $50k per accident, $10k property damage

# tags: metro, border, rgv, oil, coastal, university, plains, mountain, military,
#       dfw, houston-metro, spanish (majority Spanish-speaking households)
TEXAS = [
  # --- the five he named, then the rest of the state's largest ---
  ('houston',        'Houston',        'Harris',          ['metro','houston-metro','spanish'],
     ['pasadena','sugar-land','baytown','san-antonio']),
  ('san-antonio',    'San Antonio',    'Bexar',           ['metro','spanish','military'],
     ['austin','new-braunfels','laredo','houston']),
  ('dallas',         'Dallas',         'Dallas',          ['metro','dfw','spanish'],
     ['fort-worth','garland','irving','plano']),
  ('austin',         'Austin',         'Travis',          ['metro','university'],
     ['round-rock','san-antonio','georgetown','waco']),
  ('el-paso',        'El Paso',        'El Paso',         ['metro','border','spanish','mountain','military'],
     ['socorro','horizon-city','san-elizario','las-cruces']),
  ('fort-worth',     'Fort Worth',     'Tarrant',         ['metro','dfw'],
     ['dallas','arlington','grand-prairie','denton']),
  ('arlington',      'Arlington',      'Tarrant',         ['metro','dfw','university'],
     ['fort-worth','grand-prairie','dallas','irving']),
  ('corpus-christi', 'Corpus Christi', 'Nueces',          ['coastal','spanish','metro'],
     ['brownsville','victoria','san-antonio','laredo']),
  ('plano',          'Plano',          'Collin',          ['metro','dfw'],
     ['dallas','garland','irving','mckinney']),
  ('laredo',         'Laredo',         'Webb',            ['border','spanish','metro'],
     ['eagle-pass','rio-grande-city','san-antonio','mcallen']),
  ('lubbock',        'Lubbock',        'Lubbock',         ['plains','university'],
     ['amarillo','midland','odessa','abilene']),
  ('garland',        'Garland',        'Dallas',          ['metro','dfw','spanish'],
     ['dallas','plano','irving','mesquite']),
  ('irving',         'Irving',         'Dallas',          ['metro','dfw','spanish'],
     ['dallas','grand-prairie','arlington','garland']),
  ('amarillo',       'Amarillo',       'Potter',          ['plains'],
     ['lubbock','odessa','midland','clovis']),
  ('grand-prairie',  'Grand Prairie',  'Dallas',          ['metro','dfw','spanish'],
     ['arlington','irving','fort-worth','dallas']),

  # --- the border, river to river ---
  ('brownsville',    'Brownsville',    'Cameron',         ['border','rgv','spanish','coastal'],
     ['harlingen','mcallen','weslaco','corpus-christi']),
  ('mcallen',        'McAllen',        'Hidalgo',         ['border','rgv','spanish'],
     ['edinburg','mission','pharr','brownsville']),
  ('edinburg',       'Edinburg',       'Hidalgo',         ['rgv','spanish','university'],
     ['mcallen','pharr','mission','weslaco']),
  ('mission',        'Mission',        'Hidalgo',         ['border','rgv','spanish'],
     ['mcallen','edinburg','pharr','rio-grande-city']),
  ('pharr',          'Pharr',          'Hidalgo',         ['border','rgv','spanish'],
     ['mcallen','edinburg','weslaco','mission']),
  ('harlingen',      'Harlingen',      'Cameron',         ['rgv','spanish'],
     ['brownsville','weslaco','mcallen','pharr']),
  ('weslaco',        'Weslaco',        'Hidalgo',         ['rgv','spanish'],
     ['harlingen','pharr','mcallen','brownsville']),
  ('rio-grande-city','Rio Grande City','Starr',           ['border','rgv','spanish'],
     ['mission','mcallen','laredo','edinburg']),
  ('eagle-pass',     'Eagle Pass',     'Maverick',        ['border','spanish'],
     ['del-rio','laredo','san-antonio','uvalde']),
  ('del-rio',        'Del Rio',        'Val Verde',       ['border','spanish','military'],
     ['eagle-pass','uvalde','san-angelo','laredo']),
  ('uvalde',         'Uvalde',         'Uvalde',          ['spanish'],
     ['eagle-pass','del-rio','san-antonio','laredo']),
  ('socorro',        'Socorro',        'El Paso',         ['border','spanish'],
     ['el-paso','san-elizario','horizon-city','fabens']),
  ('horizon-city',   'Horizon City',   'El Paso',         ['border','spanish'],
     ['el-paso','socorro','san-elizario','fabens']),
  ('san-elizario',   'San Elizario',   'El Paso',         ['border','spanish'],
     ['socorro','el-paso','fabens','horizon-city']),
  ('fabens',         'Fabens',         'El Paso',         ['border','spanish'],
     ['san-elizario','socorro','el-paso','horizon-city']),
  ('anthony',        'Anthony',        'El Paso',         ['border','spanish'],
     ['el-paso','sunland-park','las-cruces','socorro']),

  # --- the rest of the Spanish-speaking map and the big secondary markets ---
  ('odessa',         'Odessa',         'Ector',           ['oil','spanish'],
     ['midland','lubbock','san-angelo','amarillo']),
  ('midland',        'Midland',        'Midland',         ['oil'],
     ['odessa','lubbock','san-angelo','amarillo']),
  ('san-angelo',     'San Angelo',     'Tom Green',       ['plains','military'],
     ['midland','odessa','abilene','del-rio']),
  ('abilene',        'Abilene',        'Taylor',          ['plains','military'],
     ['lubbock','san-angelo','fort-worth','midland']),
  ('waco',           'Waco',           'McLennan',        ['university'],
     ['austin','killeen','fort-worth','temple']),
  ('killeen',        'Killeen',        'Bell',            ['military'],
     ['temple','waco','austin','georgetown']),
  ('temple',         'Temple',         'Bell',            ['military'],
     ['killeen','waco','austin','georgetown']),
  ('pasadena',       'Pasadena',       'Harris',          ['houston-metro','spanish'],
     ['houston','baytown','sugar-land','galveston']),
  ('baytown',        'Baytown',        'Harris',          ['houston-metro','coastal'],
     ['houston','pasadena','galveston','beaumont']),
  ('sugar-land',     'Sugar Land',     'Fort Bend',       ['houston-metro'],
     ['houston','pasadena','baytown','galveston']),
  ('galveston',      'Galveston',      'Galveston',       ['coastal'],
     ['houston','baytown','pasadena','beaumont']),
  ('beaumont',       'Beaumont',       'Jefferson',       ['coastal'],
     ['baytown','houston','galveston','pasadena']),
  ('victoria',       'Victoria',       'Victoria',        ['coastal'],
     ['corpus-christi','houston','san-antonio','galveston']),
  ('new-braunfels',  'New Braunfels',  'Comal',           ['university'],
     ['san-antonio','austin','georgetown','round-rock']),
  ('round-rock',     'Round Rock',     'Williamson',      ['metro'],
     ['austin','georgetown','waco','san-antonio']),
  ('georgetown',     'Georgetown',     'Williamson',      ['metro'],
     ['round-rock','austin','killeen','temple']),
  ('denton',         'Denton',         'Denton',          ['dfw','university'],
     ['fort-worth','dallas','plano','mckinney']),
  ('mckinney',       'McKinney',       'Collin',          ['dfw'],
     ['plano','dallas','denton','garland']),
  ('mesquite',       'Mesquite',       'Dallas',          ['dfw','spanish'],
     ['garland','dallas','irving','plano']),
  ('tyler',          'Tyler',          'Smith',           ['plains'],
     ['dallas','waco','beaumont','fort-worth']),
# --- filling out the state's largest, by population ---
  ('frisco',            'Frisco',            'Collin',      ['metro','dfw'],
     ['plano','mckinney','denton','the-colony']),
  ('carrollton',        'Carrollton',        'Dallas',      ['metro','dfw','spanish'],
     ['dallas','irving','plano','lewisville']),
  ('richardson',        'Richardson',        'Dallas',      ['metro','dfw','university'],
     ['dallas','plano','garland','mesquite']),
  ('pearland',          'Pearland',          'Brazoria',    ['houston-metro'],
     ['houston','sugar-land','pasadena','league-city']),
  ('college-station',   'College Station',   'Brazos',      ['university'],
     ['bryan','waco','austin','houston']),
  ('lewisville',        'Lewisville',        'Denton',      ['dfw','spanish'],
     ['denton','carrollton','flower-mound','the-colony']),
  ('league-city',       'League City',       'Galveston',   ['houston-metro','coastal'],
     ['galveston','pearland','texas-city','houston']),
  ('allen',             'Allen',             'Collin',      ['dfw'],
     ['plano','mckinney','frisco','wylie']),
  ('wichita-falls',     'Wichita Falls',     'Wichita',     ['plains','military'],
     ['denton','fort-worth','abilene','sherman']),
  ('bryan',             'Bryan',             'Brazos',      ['university','spanish'],
     ['college-station','waco','austin','houston']),
  ('conroe',            'Conroe',            'Montgomery',  ['houston-metro'],
     ['houston','huntsville','baytown','sugar-land']),
  ('longview',          'Longview',          'Gregg',       ['plains'],
     ['tyler','sherman','beaumont','dallas']),
  ('cedar-park',        'Cedar Park',        'Williamson',  ['metro'],
     ['round-rock','austin','georgetown','san-marcos']),
  ('flower-mound',      'Flower Mound',      'Denton',      ['dfw'],
     ['lewisville','denton','grapevine','coppell']),
  ('north-richland-hills','North Richland Hills','Tarrant', ['dfw'],
     ['fort-worth','keller','bedford','grapevine']),
  ('mansfield',         'Mansfield',         'Tarrant',     ['dfw'],
     ['arlington','fort-worth','cedar-hill','grand-prairie']),
  ('rowlett',           'Rowlett',           'Dallas',      ['dfw'],
     ['garland','mesquite','wylie','rockwall']),
  ('san-marcos',        'San Marcos',        'Hays',        ['university','spanish'],
     ['new-braunfels','austin','san-antonio','round-rock']),
  ('port-arthur',       'Port Arthur',       'Jefferson',   ['coastal','spanish'],
     ['beaumont','baytown','galveston','houston']),
  ('missouri-city',     'Missouri City',     'Fort Bend',   ['houston-metro'],
     ['sugar-land','houston','pearland','pasadena']),
  ('euless',            'Euless',            'Tarrant',     ['dfw','spanish'],
     ['bedford','grapevine','arlington','irving']),
  ('desoto',            'DeSoto',            'Dallas',      ['dfw'],
     ['cedar-hill','duncanville','dallas','grand-prairie']),
  ('grapevine',         'Grapevine',         'Tarrant',     ['dfw'],
     ['euless','flower-mound','irving','keller']),
  ('cedar-hill',        'Cedar Hill',        'Dallas',      ['dfw'],
     ['desoto','duncanville','mansfield','grand-prairie']),
  ('texas-city',        'Texas City',        'Galveston',   ['coastal','spanish'],
     ['galveston','league-city','pasadena','baytown']),
  ('wylie',             'Wylie',             'Collin',      ['dfw'],
     ['rowlett','allen','plano','rockwall']),
  ('keller',            'Keller',            'Tarrant',     ['dfw'],
     ['north-richland-hills','grapevine','fort-worth','denton']),
  ('coppell',           'Coppell',           'Dallas',      ['dfw'],
     ['irving','grapevine','carrollton','flower-mound']),
  ('rockwall',          'Rockwall',          'Rockwall',    ['dfw'],
     ['rowlett','wylie','mesquite','garland']),
  ('huntsville',        'Huntsville',        'Walker',      ['university'],
     ['conroe','houston','bryan','college-station']),
  ('duncanville',       'Duncanville',       'Dallas',      ['dfw','spanish'],
     ['desoto','cedar-hill','dallas','grand-prairie']),
  ('sherman',           'Sherman',           'Grayson',     ['plains'],
     ['mckinney','denton','wichita-falls','frisco']),
  ('the-colony',        'The Colony',        'Denton',      ['dfw'],
     ['frisco','lewisville','carrollton','plano']),
  ('bedford',           'Bedford',           'Tarrant',     ['dfw'],
     ['euless','north-richland-hills','grapevine','fort-worth']),
]

NEW_MEXICO = [
  ('albuquerque',  'Albuquerque',  'Bernalillo',  ['metro','spanish','mountain','university'],
     ['rio-rancho','santa-fe','los-lunas','belen']),
  ('las-cruces',   'Las Cruces',   'Doña Ana',    ['metro','border','spanish','university'],
     ['sunland-park','new-mexico:anthony','deming','texas:el-paso']),
  ('rio-rancho',   'Rio Rancho',   'Sandoval',    ['metro'],
     ['albuquerque','santa-fe','los-lunas','belen']),
  ('santa-fe',     'Santa Fe',     'Santa Fe',    ['mountain','spanish'],
     ['albuquerque','rio-rancho','espanola','los-lunas']),
  ('roswell',      'Roswell',      'Chaves',      ['plains'],
     ['carlsbad','hobbs','clovis','alamogordo']),
  ('farmington',   'Farmington',   'San Juan',    ['plains','oil'],
     ['albuquerque','gallup','santa-fe','rio-rancho']),
  ('clovis',       'Clovis',       'Curry',       ['plains','military'],
     ['roswell','hobbs','carlsbad','texas:amarillo']),
  ('hobbs',        'Hobbs',        'Lea',         ['oil'],
     ['carlsbad','roswell','clovis','texas:odessa']),
  ('alamogordo',   'Alamogordo',   'Otero',       ['military','mountain'],
     ['las-cruces','roswell','carlsbad','texas:el-paso']),
  ('carlsbad',     'Carlsbad',     'Eddy',        ['oil'],
     ['hobbs','roswell','alamogordo','clovis']),
  ('sunland-park', 'Sunland Park', 'Doña Ana',    ['border','spanish'],
     ['las-cruces','new-mexico:anthony','deming','texas:el-paso']),
  ('deming',       'Deming',       'Luna',        ['border','spanish'],
     ['las-cruces','sunland-park','silver-city','alamogordo']),
  ('espanola',     'Española',    'Rio Arriba',  ['mountain','spanish'],
     ['santa-fe','albuquerque','rio-rancho','taos']),
  ('gallup',       'Gallup',       'McKinley',    ['plains'],
     ['farmington','albuquerque','grants','rio-rancho']),
  ('los-lunas',    'Los Lunas',    'Valencia',    ['metro','spanish'],
     ['albuquerque','belen','rio-rancho','santa-fe']),
# --- out to the forty largest in the state ---
  ('chaparral',    'Chaparral',    'Doña Ana',   ['border','spanish'],
     ['las-cruces','sunland-park','anthony','texas:el-paso']),
  ('las-vegas',    'Las Vegas',    'San Miguel', ['mountain','spanish'],
     ['santa-fe','espanola','raton','albuquerque']),
  ('portales',     'Portales',     'Roosevelt',  ['plains'],
     ['clovis','roswell','hobbs','texas:lubbock']),
  ('artesia',      'Artesia',      'Eddy',       ['oil'],
     ['carlsbad','roswell','hobbs','alamogordo']),
  ('lovington',    'Lovington',    'Lea',        ['oil','spanish'],
     ['hobbs','carlsbad','artesia','texas:odessa']),
  ('silver-city',  'Silver City',  'Grant',      ['mountain','university'],
     ['deming','las-cruces','bayard','truth-or-consequences']),
  ('bernalillo',   'Bernalillo',   'Sandoval',   ['metro','spanish'],
     ['rio-rancho','albuquerque','santa-fe','corrales']),
  ('grants',       'Grants',       'Cibola',     ['plains','spanish'],
     ['gallup','albuquerque','milan','rio-rancho']),
  ('socorro',      'Socorro',      'Socorro',    ['spanish','university'],
     ['albuquerque','belen','truth-or-consequences','los-lunas']),
  ('corrales',     'Corrales',     'Sandoval',   ['metro'],
     ['rio-rancho','albuquerque','bernalillo','santa-fe']),
  ('ruidoso',      'Ruidoso',      'Lincoln',    ['mountain'],
     ['alamogordo','roswell','carlsbad','artesia']),
  ('aztec',        'Aztec',        'San Juan',   ['plains','oil'],
     ['farmington','bloomfield','kirtland','gallup']),
  ('bloomfield',   'Bloomfield',   'San Juan',   ['oil'],
     ['farmington','aztec','kirtland','gallup']),
  ('truth-or-consequences','Truth or Consequences','Sierra', ['mountain'],
     ['las-cruces','socorro','silver-city','deming']),
  ('belen',        'Belen',        'Valencia',   ['spanish'],
     ['los-lunas','albuquerque','socorro','rio-rancho']),
  ('anthony',      'Anthony',      'Doña Ana',   ['border','spanish'],
     ['sunland-park','las-cruces','chaparral','texas:el-paso']),
  ('raton',        'Raton',        'Colfax',     ['mountain'],
     ['las-vegas','santa-fe','espanola','taos']),
  ('los-alamos',   'Los Alamos',   'Los Alamos', ['mountain','university'],
     ['santa-fe','espanola','rio-rancho','albuquerque']),
  ('taos',         'Taos',         'Taos',       ['mountain','spanish'],
     ['espanola','santa-fe','raton','las-vegas']),
  ('tucumcari',    'Tucumcari',    'Quay',       ['plains'],
     ['santa-rosa','clovis','las-vegas','portales']),
  ('milan',        'Milan',        'Cibola',     ['plains','spanish'],
     ['grants','gallup','albuquerque','rio-rancho']),
  ('eunice',       'Eunice',       'Lea',        ['oil'],
     ['hobbs','lovington','carlsbad','jal']),
  ('santa-rosa',   'Santa Rosa',   'Guadalupe',  ['plains','spanish'],
     ['tucumcari','las-vegas','santa-fe','clovis']),
  ('bayard',       'Bayard',       'Grant',      ['mountain','spanish'],
     ['silver-city','deming','las-cruces','truth-or-consequences']),
  ('hatch',        'Hatch',        'Doña Ana',   ['spanish'],
     ['las-cruces','deming','truth-or-consequences','sunland-park']),
  ('jal',          'Jal',          'Lea',        ['oil'],
     ['eunice','hobbs','lovington','carlsbad']),
  ('kirtland',     'Kirtland',     'San Juan',   ['oil'],
     ['farmington','bloomfield','aztec','gallup']),
  ('edgewood',     'Edgewood',     'Santa Fe',   ['mountain'],
     ['moriarty','albuquerque','santa-fe','rio-rancho']),
  ('moriarty',     'Moriarty',     'Torrance',   ['plains'],
     ['edgewood','albuquerque','santa-fe','los-lunas']),
]

SKIP = set()


# One checkable fact per city, used to give every page a paragraph nothing else
# has. Roads and geography only — no populations, no averages, nothing that
# would need a citation we cannot give.
ROADS = {
  # Texas
  'houston':        'I-45, I-10 and the 610 loop',
  'san-antonio':    'I-35, I-10 and Loop 410',
  'dallas':         'I-35E, I-30 and the 635 loop',
  'austin':         'I-35 straight through the middle of town',
  'el-paso':        'I-10, running the length of the city',
  'fort-worth':     'I-35W, I-30 and I-20',
  'arlington':      'I-30 and I-20, with the stadium traffic between them',
  'corpus-christi': 'I-37 down from San Antonio',
  'plano':          'US-75, the Central Expressway',
  'laredo':         'the southern end of I-35',
  'lubbock':        'I-27 and the Loop 289 ring',
  'garland':        'I-635 and the President George Bush Turnpike',
  'irving':         'SH-183 and I-635, with DFW airport on the doorstep',
  'amarillo':       'I-40 crossing I-27',
  'grand-prairie':  'I-30 and SH-161',
  'brownsville':    'US-77 and I-69E',
  'mcallen':        'US-83 and I-2, the Expressway',
  'edinburg':       'US-281',
  'mission':        'US-83 and I-2',
  'pharr':          'US-281 meeting I-2',
  'harlingen':      'US-77 and I-69E crossing I-2',
  'weslaco':        'US-83 and I-2',
  'rio-grande-city':'US-83, hard against the river',
  'eagle-pass':     'US-57 and US-277',
  'del-rio':        'US-90 and US-277',
  'uvalde':         'US-90 crossing US-83',
  'socorro':        'the I-10 corridor southeast of El Paso',
  'horizon-city':   'the I-10 corridor east of El Paso',
  'san-elizario':   'the river road below the I-10 corridor',
  'fabens':         'I-10, well down the valley from El Paso',
  'anthony':        'I-10 at the New Mexico state line',
  'odessa':         'I-20 through the Permian Basin',
  'midland':        'I-20 through the Permian Basin',
  'san-angelo':     'US-87 and US-67',
  'abilene':        'I-20',
  'waco':           'I-35 between Dallas and Austin',
  'killeen':        'US-190 and I-14, next to Fort Cavazos',
  'temple':         'I-35',
  'pasadena':       'SH-225 and Beltway 8, along the ship channel',
  'baytown':        'I-10 east of Houston',
  'sugar-land':     'US-59 and I-69',
  'galveston':      'the southern end of I-45, out on the island',
  'beaumont':       'I-10 near the Louisiana line',
  'victoria':       'US-59 crossing US-77',
  'new-braunfels':  'I-35 between San Antonio and Austin',
  'round-rock':     'I-35 north of Austin',
  'georgetown':     'I-35 at the top of the Austin corridor',
  'denton':         'the point where I-35 splits into I-35E and I-35W',
  'mckinney':       'US-75',
  'mesquite':       'I-635, I-30 and US-80',
  'tyler':          'US-69 and Loop 323',
  # New Mexico
  'albuquerque':    'the crossing of I-25 and I-40',
  'las-cruces':     'the crossing of I-10 and I-25',
  'rio-rancho':     'US-550 above Albuquerque',
  'santa-fe':       'I-25 at the top of the Rio Grande corridor',
  'roswell':        'US-285 crossing US-70',
  'farmington':     'US-64 and US-550 in the Four Corners',
  'clovis':         'US-60 and US-84 near the Texas line',
  'hobbs':          'US-62 and US-180 on the Texas line',
  'alamogordo':     'US-54 and US-70 below the Sacramentos',
  'carlsbad':       'US-285 and US-62',
  'sunland-park':   'the state line, tucked between El Paso and the river',
  'deming':         'I-10 west of Las Cruces',
  'espanola':       'US-84 and US-285 north of Santa Fe',
  'gallup':         'I-40 near the Arizona line',
  'los-lunas':      'I-25 below Albuquerque',

  # Texas, filling out the largest
  'frisco':            'the Dallas North Tollway and SH-121',
  'carrollton':        'I-35E and the President George Bush Turnpike',
  'richardson':        'US-75 and the 635 loop',
  'pearland':          'SH-288 south of Houston',
  'college-station':   'SH-6 through the Brazos Valley',
  'lewisville':        'I-35E north of Dallas',
  'league-city':       'I-45 between Houston and Galveston',
  'allen':             'US-75',
  'wichita-falls':     'US-287 and I-44',
  'bryan':             'SH-6 and SH-21',
  'conroe':            'I-45 north of Houston',
  'longview':          'I-20 and US-259',
  'cedar-park':        'US-183A north of Austin',
  'flower-mound':      'SH-121 and FM-2499',
  'north-richland-hills':'SH-121 and Loop 820',
  'mansfield':         'US-287 and SH-360',
  'rowlett':           'I-30 and the President George Bush Turnpike',
  'san-marcos':        'I-35 between Austin and San Antonio',
  'port-arthur':       'SH-73 and SH-87 on the Gulf',
  'missouri-city':     'US-90A and the Fort Bend Parkway',
  'euless':            'SH-183 and SH-360, next to DFW',
  'desoto':            'I-35E and I-20',
  'grapevine':         'SH-114 and SH-121 beside the lake',
  'cedar-hill':        'US-67 and FM-1382',
  'texas-city':        'I-45 and SH-146 on the bay',
  'wylie':             'SH-78 northeast of Dallas',
  'keller':            'US-377 and SH-114',
  'coppell':           'SH-121 and Belt Line, on the DFW fence',
  'rockwall':          'I-30 across Lake Ray Hubbard',
  'huntsville':        'I-45 north of Conroe',
  'duncanville':       'US-67 and I-20',
  'sherman':           'US-75 near the Oklahoma line',
  'the-colony':        'SH-121 along the lake',
  'bedford':           'SH-121 and Loop 820',
  # New Mexico, out to the forty largest
  'chaparral':         'NM-213 between Las Cruces and El Paso',
  'las-vegas':         'I-25 in the northeast highlands',
  'portales':          'US-70 near the Texas line',
  'artesia':           'US-285 and US-82',
  'lovington':         'US-82 and NM-18',
  'silver-city':       'US-180 in the Gila country',
  'bernalillo':        'I-25 and US-550 north of Albuquerque',
  'grants':            'I-40 west of Albuquerque',
  'socorro':           'I-25 down the Rio Grande',
  'corrales':          'the river road between Rio Rancho and Albuquerque',
  'ruidoso':           'US-70 up in the Sacramentos',
  'aztec':             'US-550 and NM-516',
  'bloomfield':        'US-64 and US-550',
  'truth-or-consequences':'I-25 beside Elephant Butte',
  'belen':             'I-25 south of Los Lunas',
  'anthony':           'I-10 at the Texas state line',
  'raton':             'I-25 at Raton Pass',
  'los-alamos':        'NM-502 up on the Pajarito Plateau',
  'taos':              'US-64 and NM-68 in the high country',
  'tucumcari':         'I-40 in the eastern plains',
  'milan':             'I-40 beside Grants',
  'eunice':            'NM-18 on the Texas line',
  'santa-rosa':        'I-40 and US-54',
  'bayard':            'US-180 in the Mining District',
  'hatch':             'I-25 and NM-26 in the chile valley',
  'jal':               'NM-18 in the far southeast corner',
  'kirtland':          'US-64 west of Farmington',
  'edgewood':          'I-40 east of the Sandias',
  'moriarty':          'I-40 and US-66 on the Estancia plain',
}
