"""The city list behind the local landing pages.

Each row is (slug, name, county, tags, neighbors).

`tags` decides which of the written sections a page gets, and it is the reason
these are not doorway pages: a border city page argues about Mexican policies
and foreign licenses, an oil-basin page argues about work trucks and commute
mileage, a coastal page argues about wind and flood. Two cities with the same
tags still differ by county, by state minimums and by who they link to.

Nothing here is a statistic. Counties, state minimum limits and which cities sit
on the river are all checkable facts. Average premiums, population counts and
"drivers in Dallas save $X" are not in this file on purpose — inventing them
would be the fastest way to make the whole set worthless.

Only Texas and New Mexico appear, because those are the two licenses the agency
holds. A landing page for a city we cannot write in is a page that wastes the
visitor's time.
"""
import i18n


TX_MIN = '30/60/25'   # $30k per person, $60k per accident, $25k property damage
NM_MIN = '25/50/10'   # $25k per person, $50k per accident, $10k property damage

# tags: metro, border, rgv, oil, coastal, university, plains, mountain, military,
#       dfw, houston-metro, spanish (majority Spanish-speaking households)
TEXAS = [
  # --- the five he named, then the rest of the state's largest ---
  ('houston',        'Houston',        'Harris',          ['metro','houston-metro','spanish'],
     ['pasadena','sugar-land','baytown','san-antonio']),
  ('san-antonio',    'San Antonio',    'Bexar',           ['metro','spanish','military'],
     ['austin','new-braunfels','laredo','houston']),
  ('dallas',         'Dallas',         'Dallas',          ['metro','dfw','spanish'],
     ['fort-worth','garland','irving','plano']),
  ('austin',         'Austin',         'Travis',          ['metro','university'],
     ['round-rock','san-antonio','georgetown','waco']),
  ('el-paso',        'El Paso',        'El Paso',         ['metro','border','spanish','mountain','military'],
     ['socorro','horizon-city','san-elizario','las-cruces']),
  ('fort-worth',     'Fort Worth',     'Tarrant',         ['metro','dfw'],
     ['dallas','arlington','grand-prairie','denton']),
  ('arlington',      'Arlington',      'Tarrant',         ['metro','dfw','university'],
     ['fort-worth','grand-prairie','dallas','irving']),
  ('corpus-christi', 'Corpus Christi', 'Nueces',          ['coastal','spanish','metro'],
     ['brownsville','victoria','san-antonio','laredo']),
  ('plano',          'Plano',          'Collin',          ['metro','dfw'],
     ['dallas','garland','irving','mckinney']),
  ('laredo',         'Laredo',         'Webb',            ['border','spanish','metro'],
     ['eagle-pass','rio-grande-city','san-antonio','mcallen']),
  ('lubbock',        'Lubbock',        'Lubbock',         ['plains','university'],
     ['amarillo','midland','odessa','abilene']),
  ('garland',        'Garland',        'Dallas',          ['metro','dfw','spanish'],
     ['dallas','plano','irving','mesquite']),
  ('irving',         'Irving',         'Dallas',          ['metro','dfw','spanish'],
     ['dallas','grand-prairie','arlington','garland']),
  ('amarillo',       'Amarillo',       'Potter',          ['plains'],
     ['lubbock','odessa','midland','clovis']),
  ('grand-prairie',  'Grand Prairie',  'Dallas',          ['metro','dfw','spanish'],
     ['arlington','irving','fort-worth','dallas']),

  # --- the border, river to river ---
  ('brownsville',    'Brownsville',    'Cameron',         ['border','rgv','spanish','coastal'],
     ['harlingen','mcallen','weslaco','corpus-christi']),
  ('mcallen',        'McAllen',        'Hidalgo',         ['border','rgv','spanish'],
     ['edinburg','mission','pharr','brownsville']),
  ('edinburg',       'Edinburg',       'Hidalgo',         ['rgv','spanish','university'],
     ['mcallen','pharr','mission','weslaco']),
  ('mission',        'Mission',        'Hidalgo',         ['border','rgv','spanish'],
     ['mcallen','edinburg','pharr','rio-grande-city']),
  ('pharr',          'Pharr',          'Hidalgo',         ['border','rgv','spanish'],
     ['mcallen','edinburg','weslaco','mission']),
  ('harlingen',      'Harlingen',      'Cameron',         ['rgv','spanish'],
     ['brownsville','weslaco','mcallen','pharr']),
  ('weslaco',        'Weslaco',        'Hidalgo',         ['rgv','spanish'],
     ['harlingen','pharr','mcallen','brownsville']),
  ('rio-grande-city','Rio Grande City','Starr',           ['border','rgv','spanish'],
     ['mission','mcallen','laredo','edinburg']),
  ('eagle-pass',     'Eagle Pass',     'Maverick',        ['border','spanish'],
     ['del-rio','laredo','san-antonio','uvalde']),
  ('del-rio',        'Del Rio',        'Val Verde',       ['border','spanish','military'],
     ['eagle-pass','uvalde','san-angelo','laredo']),
  ('uvalde',         'Uvalde',         'Uvalde',          ['spanish'],
     ['eagle-pass','del-rio','san-antonio','laredo']),
  ('socorro',        'Socorro',        'El Paso',         ['border','spanish'],
     ['el-paso','san-elizario','horizon-city','fabens']),
  ('horizon-city',   'Horizon City',   'El Paso',         ['border','spanish'],
     ['el-paso','socorro','san-elizario','fabens']),
  ('san-elizario',   'San Elizario',   'El Paso',         ['border','spanish'],
     ['socorro','el-paso','fabens','horizon-city']),
  ('fabens',         'Fabens',         'El Paso',         ['border','spanish'],
     ['san-elizario','socorro','el-paso','horizon-city']),
  ('anthony',        'Anthony',        'El Paso',         ['border','spanish'],
     ['el-paso','sunland-park','las-cruces','socorro']),

  # --- the rest of the Spanish-speaking map and the big secondary markets ---
  ('odessa',         'Odessa',         'Ector',           ['oil','spanish'],
     ['midland','lubbock','san-angelo','amarillo']),
  ('midland',        'Midland',        'Midland',         ['oil'],
     ['odessa','lubbock','san-angelo','amarillo']),
  ('san-angelo',     'San Angelo',     'Tom Green',       ['plains','military'],
     ['midland','odessa','abilene','del-rio']),
  ('abilene',        'Abilene',        'Taylor',          ['plains','military'],
     ['lubbock','san-angelo','fort-worth','midland']),
  ('waco',           'Waco',           'McLennan',        ['university'],
     ['austin','killeen','fort-worth','temple']),
  ('killeen',        'Killeen',        'Bell',            ['military'],
     ['temple','waco','austin','georgetown']),
  ('temple',         'Temple',         'Bell',            ['military'],
     ['killeen','waco','austin','georgetown']),
  ('pasadena',       'Pasadena',       'Harris',          ['houston-metro','spanish'],
     ['houston','baytown','sugar-land','galveston']),
  ('baytown',        'Baytown',        'Harris',          ['houston-metro','coastal'],
     ['houston','pasadena','galveston','beaumont']),
  ('sugar-land',     'Sugar Land',     'Fort Bend',       ['houston-metro'],
     ['houston','pasadena','baytown','galveston']),
  ('galveston',      'Galveston',      'Galveston',       ['coastal'],
     ['houston','baytown','pasadena','beaumont']),
  ('beaumont',       'Beaumont',       'Jefferson',       ['coastal'],
     ['baytown','houston','galveston','pasadena']),
  ('victoria',       'Victoria',       'Victoria',        ['coastal'],
     ['corpus-christi','houston','san-antonio','galveston']),
  ('new-braunfels',  'New Braunfels',  'Comal',           ['university'],
     ['san-antonio','austin','georgetown','round-rock']),
  ('round-rock',     'Round Rock',     'Williamson',      ['metro'],
     ['austin','georgetown','waco','san-antonio']),
  ('georgetown',     'Georgetown',     'Williamson',      ['metro'],
     ['round-rock','austin','killeen','temple']),
  ('denton',         'Denton',         'Denton',          ['dfw','university'],
     ['fort-worth','dallas','plano','mckinney']),
  ('mckinney',       'McKinney',       'Collin',          ['dfw'],
     ['plano','dallas','denton','garland']),
  ('mesquite',       'Mesquite',       'Dallas',          ['dfw','spanish'],
     ['garland','dallas','irving','plano']),
  ('tyler',          'Tyler',          'Smith',           ['plains'],
     ['dallas','waco','beaumont','fort-worth']),
# --- filling out the state's largest, by population ---
  ('frisco',            'Frisco',            'Collin',      ['metro','dfw'],
     ['plano','mckinney','denton','the-colony']),
  ('carrollton',        'Carrollton',        'Dallas',      ['metro','dfw','spanish'],
     ['dallas','irving','plano','lewisville']),
  ('richardson',        'Richardson',        'Dallas',      ['metro','dfw','university'],
     ['dallas','plano','garland','mesquite']),
  ('pearland',          'Pearland',          'Brazoria',    ['houston-metro'],
     ['houston','sugar-land','pasadena','league-city']),
  ('college-station',   'College Station',   'Brazos',      ['university'],
     ['bryan','waco','austin','houston']),
  ('lewisville',        'Lewisville',        'Denton',      ['dfw','spanish'],
     ['denton','carrollton','flower-mound','the-colony']),
  ('league-city',       'League City',       'Galveston',   ['houston-metro','coastal'],
     ['galveston','pearland','texas-city','houston']),
  ('allen',             'Allen',             'Collin',      ['dfw'],
     ['plano','mckinney','frisco','wylie']),
  ('wichita-falls',     'Wichita Falls',     'Wichita',     ['plains','military'],
     ['denton','fort-worth','abilene','sherman']),
  ('bryan',             'Bryan',             'Brazos',      ['university','spanish'],
     ['college-station','waco','austin','houston']),
  ('conroe',            'Conroe',            'Montgomery',  ['houston-metro'],
     ['houston','huntsville','baytown','sugar-land']),
  ('longview',          'Longview',          'Gregg',       ['plains'],
     ['tyler','sherman','beaumont','dallas']),
  ('cedar-park',        'Cedar Park',        'Williamson',  ['metro'],
     ['round-rock','austin','georgetown','san-marcos']),
  ('flower-mound',      'Flower Mound',      'Denton',      ['dfw'],
     ['lewisville','denton','grapevine','coppell']),
  ('north-richland-hills','North Richland Hills','Tarrant', ['dfw'],
     ['fort-worth','keller','bedford','grapevine']),
  ('mansfield',         'Mansfield',         'Tarrant',     ['dfw'],
     ['arlington','fort-worth','cedar-hill','grand-prairie']),
  ('rowlett',           'Rowlett',           'Dallas',      ['dfw'],
     ['garland','mesquite','wylie','rockwall']),
  ('san-marcos',        'San Marcos',        'Hays',        ['university','spanish'],
     ['new-braunfels','austin','san-antonio','round-rock']),
  ('port-arthur',       'Port Arthur',       'Jefferson',   ['coastal','spanish'],
     ['beaumont','baytown','galveston','houston']),
  ('missouri-city',     'Missouri City',     'Fort Bend',   ['houston-metro'],
     ['sugar-land','houston','pearland','pasadena']),
  ('euless',            'Euless',            'Tarrant',     ['dfw','spanish'],
     ['bedford','grapevine','arlington','irving']),
  ('desoto',            'DeSoto',            'Dallas',      ['dfw'],
     ['cedar-hill','duncanville','dallas','grand-prairie']),
  ('grapevine',         'Grapevine',         'Tarrant',     ['dfw'],
     ['euless','flower-mound','irving','keller']),
  ('cedar-hill',        'Cedar Hill',        'Dallas',      ['dfw'],
     ['desoto','duncanville','mansfield','grand-prairie']),
  ('texas-city',        'Texas City',        'Galveston',   ['coastal','spanish'],
     ['galveston','league-city','pasadena','baytown']),
  ('wylie',             'Wylie',             'Collin',      ['dfw'],
     ['rowlett','allen','plano','rockwall']),
  ('keller',            'Keller',            'Tarrant',     ['dfw'],
     ['north-richland-hills','grapevine','fort-worth','denton']),
  ('coppell',           'Coppell',           'Dallas',      ['dfw'],
     ['irving','grapevine','carrollton','flower-mound']),
  ('rockwall',          'Rockwall',          'Rockwall',    ['dfw'],
     ['rowlett','wylie','mesquite','garland']),
  ('huntsville',        'Huntsville',        'Walker',      ['university'],
     ['conroe','houston','bryan','college-station']),
  ('duncanville',       'Duncanville',       'Dallas',      ['dfw','spanish'],
     ['desoto','cedar-hill','dallas','grand-prairie']),
  ('sherman',           'Sherman',           'Grayson',     ['plains'],
     ['mckinney','denton','wichita-falls','frisco']),
  ('the-colony',        'The Colony',        'Denton',      ['dfw'],
     ['frisco','lewisville','carrollton','plano']),
  ('bedford',           'Bedford',           'Tarrant',     ['dfw'],
     ['euless','north-richland-hills','grapevine','fort-worth']),
]

NEW_MEXICO = [
  ('albuquerque',  'Albuquerque',  'Bernalillo',  ['metro','spanish','mountain','university'],
     ['rio-rancho','santa-fe','los-lunas','belen']),
  ('las-cruces',   'Las Cruces',   'Doña Ana',    ['metro','border','spanish','university'],
     ['sunland-park','new-mexico:anthony','deming','texas:el-paso']),
  ('rio-rancho',   'Rio Rancho',   'Sandoval',    ['metro'],
     ['albuquerque','santa-fe','los-lunas','belen']),
  ('santa-fe',     'Santa Fe',     'Santa Fe',    ['mountain','spanish'],
     ['albuquerque','rio-rancho','espanola','los-lunas']),
  ('roswell',      'Roswell',      'Chaves',      ['plains'],
     ['carlsbad','hobbs','clovis','alamogordo']),
  ('farmington',   'Farmington',   'San Juan',    ['plains','oil'],
     ['albuquerque','gallup','santa-fe','rio-rancho']),
  ('clovis',       'Clovis',       'Curry',       ['plains','military'],
     ['roswell','hobbs','carlsbad','texas:amarillo']),
  ('hobbs',        'Hobbs',        'Lea',         ['oil'],
     ['carlsbad','roswell','clovis','texas:odessa']),
  ('alamogordo',   'Alamogordo',   'Otero',       ['military','mountain'],
     ['las-cruces','roswell','carlsbad','texas:el-paso']),
  ('carlsbad',     'Carlsbad',     'Eddy',        ['oil'],
     ['hobbs','roswell','alamogordo','clovis']),
  ('sunland-park', 'Sunland Park', 'Doña Ana',    ['border','spanish'],
     ['las-cruces','new-mexico:anthony','deming','texas:el-paso']),
  ('deming',       'Deming',       'Luna',        ['border','spanish'],
     ['las-cruces','sunland-park','silver-city','alamogordo']),
  ('espanola',     'Española',    'Rio Arriba',  ['mountain','spanish'],
     ['santa-fe','albuquerque','rio-rancho','taos']),
  ('gallup',       'Gallup',       'McKinley',    ['plains'],
     ['farmington','albuquerque','grants','rio-rancho']),
  ('los-lunas',    'Los Lunas',    'Valencia',    ['metro','spanish'],
     ['albuquerque','belen','rio-rancho','santa-fe']),
# --- out to the forty largest in the state ---
  ('chaparral',    'Chaparral',    'Doña Ana',   ['border','spanish'],
     ['las-cruces','sunland-park','anthony','texas:el-paso']),
  ('las-vegas',    'Las Vegas',    'San Miguel', ['mountain','spanish'],
     ['santa-fe','espanola','raton','albuquerque']),
  ('portales',     'Portales',     'Roosevelt',  ['plains'],
     ['clovis','roswell','hobbs','texas:lubbock']),
  ('artesia',      'Artesia',      'Eddy',       ['oil'],
     ['carlsbad','roswell','hobbs','alamogordo']),
  ('lovington',    'Lovington',    'Lea',        ['oil','spanish'],
     ['hobbs','carlsbad','artesia','texas:odessa']),
  ('silver-city',  'Silver City',  'Grant',      ['mountain','university'],
     ['deming','las-cruces','bayard','truth-or-consequences']),
  ('bernalillo',   'Bernalillo',   'Sandoval',   ['metro','spanish'],
     ['rio-rancho','albuquerque','santa-fe','corrales']),
  ('grants',       'Grants',       'Cibola',     ['plains','spanish'],
     ['gallup','albuquerque','milan','rio-rancho']),
  ('socorro',      'Socorro',      'Socorro',    ['spanish','university'],
     ['albuquerque','belen','truth-or-consequences','los-lunas']),
  ('corrales',     'Corrales',     'Sandoval',   ['metro'],
     ['rio-rancho','albuquerque','bernalillo','santa-fe']),
  ('ruidoso',      'Ruidoso',      'Lincoln',    ['mountain'],
     ['alamogordo','roswell','carlsbad','artesia']),
  ('aztec',        'Aztec',        'San Juan',   ['plains','oil'],
     ['farmington','bloomfield','kirtland','gallup']),
  ('bloomfield',   'Bloomfield',   'San Juan',   ['oil'],
     ['farmington','aztec','kirtland','gallup']),
  ('truth-or-consequences','Truth or Consequences','Sierra', ['mountain'],
     ['las-cruces','socorro','silver-city','deming']),
  ('belen',        'Belen',        'Valencia',   ['spanish'],
     ['los-lunas','albuquerque','socorro','rio-rancho']),
  ('anthony',      'Anthony',      'Doña Ana',   ['border','spanish'],
     ['sunland-park','las-cruces','chaparral','texas:el-paso']),
  ('raton',        'Raton',        'Colfax',     ['mountain'],
     ['las-vegas','santa-fe','espanola','taos']),
  ('los-alamos',   'Los Alamos',   'Los Alamos', ['mountain','university'],
     ['santa-fe','espanola','rio-rancho','albuquerque']),
  ('taos',         'Taos',         'Taos',       ['mountain','spanish'],
     ['espanola','santa-fe','raton','las-vegas']),
  ('tucumcari',    'Tucumcari',    'Quay',       ['plains'],
     ['santa-rosa','clovis','las-vegas','portales']),
  ('milan',        'Milan',        'Cibola',     ['plains','spanish'],
     ['grants','gallup','albuquerque','rio-rancho']),
  ('eunice',       'Eunice',       'Lea',        ['oil'],
     ['hobbs','lovington','carlsbad','jal']),
  ('santa-rosa',   'Santa Rosa',   'Guadalupe',  ['plains','spanish'],
     ['tucumcari','las-vegas','santa-fe','clovis']),
  ('bayard',       'Bayard',       'Grant',      ['mountain','spanish'],
     ['silver-city','deming','las-cruces','truth-or-consequences']),
  ('hatch',        'Hatch',        'Doña Ana',   ['spanish'],
     ['las-cruces','deming','truth-or-consequences','sunland-park']),
  ('jal',          'Jal',          'Lea',        ['oil'],
     ['eunice','hobbs','lovington','carlsbad']),
  ('kirtland',     'Kirtland',     'San Juan',   ['oil'],
     ['farmington','bloomfield','aztec','gallup']),
  ('edgewood',     'Edgewood',     'Santa Fe',   ['mountain'],
     ['moriarty','albuquerque','santa-fe','rio-rancho']),
  ('moriarty',     'Moriarty',     'Torrance',   ['plains'],
     ['edgewood','albuquerque','santa-fe','los-lunas']),
]

SKIP = set()


# One checkable fact per city, used to give every page a paragraph nothing else
# has. Roads and geography only — no populations, no averages, nothing that
# would need a citation we cannot give.
#
# The phrases are copy — "I-45, I-10 and the 610 loop" has to read as Spanish
# on the Spanish page — so they are cities.roads.<state>.<slug> in
# locales/<lang>/cities.json, road names kept as they are.
#
# Keyed by state as well as slug, like every other per-city table. It used to
# be keyed by slug alone, and Socorro and Anthony exist in both states: when
# this was a dict literal the New Mexico entry silently replaced the Texas one,
# so Socorro, TX told visitors its traffic ran on "I-25 down the Rio Grande"
# and Anthony, TX that it sat "at the Texas state line".
def road(state, slug):
    """The road phrase for a city in the language being rendered, or None for
    a city that has none. A phrase the English has and the Spanish lacks is an
    error, not a missing paragraph."""
    key = 'cities.roads.%s.%s' % (state, slug)
    if not i18n.has(key, i18n.DEFAULT):
        return None
    return i18n.t(key)
